### ISSUE TITLE
Running First Job Error -- UserWarning: Failed to load image Python extension: /opt/conda/envs/Homekit2020/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowEllb

### ISSUE THREAD

**Issue by mnodini** [behavioral-data/Homekit2020#12]
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/77136138/186997850-44afe03b-9de8-4fb1-b07f-ba47de9f21ff.png">

**Comment by TheMikeMerrill** [comment]
Hard to be sure, but this looks like you tried to run the model on a computer without GPUs (or perhaps theres some issue with your CUDA installation).

If you're trying to run on cpus, you could try passing the flag `--trainer.accelerator=cpu`.

We could also consider changing the default to `--trainer.accelerator=auto`

**Comment by mnodini** [comment]
It's strange because I'm launching my instance with 2 GPUs, but for some reason when I'm in the conda environment I don't think it's able to access them for some reason. I'll do a little more troubleshooting then post my findings.

**Comment by TheMikeMerrill** [comment]
This could also be related to #10 

Maybe try playing around with your `cudatoolkit` version? Seems like a driver-related issue to me. Please let me know if you end up fixing this, seems important :)

**Comment by mnodini** [comment]
With --trainer.accelerator=auto:

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/77136138/187287102-d77ec3d4-3e12-47db-8b37-114b31e71a33.png">

With --trainer.accelerator=cpu

<img width="1338" alt="image" src="https://user-images.githubusercontent.com/77136138/187287309-3d4e9c98-5048-4408-be25-d918825cad06.png">

Cudatoolkit version in conda environment:

<img width="560" alt="image" src="https://user-images.githubusercontent.com/77136138/187287730-e1901976-d0a3-4010-9853-9b1bea4b6364.png">

Cudatoolkit version in base environment:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/77136138/187288011-76e91462-4a07-41a1-94ac-a824327e6a68.png">

**After upgrading Cudatoolkit in conda environment to 11.7.0** with trainer.accelerator=cpu

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/77136138/187289873-a4b2d655-ceb8-42e3-8cfe-d676edfec073.png">

With trainer.accelerator=auto

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/77136138/187290044-e55ea940-9522-4baf-97d8-acbc31ca537d.png">

Without trainer.accelerator

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/77136138/187290214-02f9f495-768f-4832-852b-5941c4d29d94.png">

Instance Settings:

2 GPUs
8 Cores
120GB RAM

**Comment by mnodini** [comment]
The failed to load image Python Extension bug is fixed by downgrading torchvision to 0.10.0 solved from this comment:

https://github.com/pytorch/vision/issues/5919#issuecomment-1142350615
