### ISSUE TITLE
Bug with pyspark 3.3.0 "Running your first job"

### ISSUE THREAD

**Issue by mnodini** [behavioral-data/Homekit2020#8]
With latest version of pyspark:

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/77136138/186020151-e63904e7-a922-4a82-afba-c8ee54345c0b.png">

After downgrading to 3.1.2, it runs successfully

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/77136138/186022069-8e363015-ddf3-4964-90db-3c857006fb0a.png">

**Comment by TheMikeMerrill** [comment]
Hm interesting - looks like 3.1.2 is already specified in `environment.yaml`. Any idea how 3.3.0 could have been installed?
